enum ERRORS
{
    EXTRA_PARAMS = 1, NOT_ENOUGH_PARAMS, 
    FILE_ERROR, 
    WRONG_ARGUMENTS, 
    INVALID_FILE, 
    NOT_ENOUGH_MEMORY,
    DIR_ALREADY_EXISTS,
    INCOMPLETE_FILE,
    OPTIONAL_PARAMETER_PLACEMENT,
    WRITE_ERROR
};